# Generated by Django 4.0 on 2022-04-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerLine1', models.CharField(blank=True, max_length=20, null=True)),
                ('customerLine2', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerEmail1', models.CharField(blank=True, max_length=225, null=True)),
                ('customerEmail2', models.CharField(blank=True, max_length=225, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=225, null=True)),
                ('instagram', models.CharField(blank=True, max_length=225, null=True)),
                ('twitter', models.CharField(blank=True, max_length=225, null=True)),
                ('youtube', models.CharField(blank=True, max_length=225, null=True)),
                ('tiktok', models.CharField(blank=True, max_length=225, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Whatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerCare', models.CharField(blank=True, max_length=20, null=True)),
                ('customerBot', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
