# Generated by Django 4.0 on 2022-04-07 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputAmount', models.BigIntegerField(default=0)),
                ('outputAmount', models.BigIntegerField(blank=True, default=0, null=True)),
                ('returns', models.BigIntegerField(blank=True, default=0, null=True)),
                ('username', models.CharField(blank=True, max_length=225, null=True)),
                ('gain', models.BooleanField(default=False)),
                ('loss', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to='auth.user')),
            ],
        ),
    ]
