# Generated by Django 4.0 on 2022-04-08 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_clienttradehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previousBalance', models.BigIntegerField(blank=True, default=0, null=True)),
                ('newBalance', models.BigIntegerField(blank=True, default=0, null=True)),
                ('growth', models.BigIntegerField(blank=True, default=0, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_source', to='Management.dailytrade')),
            ],
        ),
    ]
