# Generated by Django 4.0 on 2022-04-07 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('General_Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.IntegerField(default=0, max_length=10)),
                ('bank_name', models.CharField(max_length=225)),
                ('allowed', models.BooleanField(default=True)),
                ('block', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='my bank', max_length=225)),
                ('acct_name', models.CharField(max_length=225)),
                ('acct_number', models.CharField(max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('verified_failed', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_bank', to='transaction.bank')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acct_owner', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('username', models.CharField(blank=True, max_length=225, null=True)),
                ('ref_number', models.CharField(blank=True, max_length=15, null=True)),
                ('transactionID', models.CharField(max_length=20, unique=True)),
                ('pending', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_bank', to='transaction.withdrawaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_user', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('senderName', models.CharField(blank=True, default='null', max_length=225, null=True)),
                ('recipientName', models.CharField(blank=True, max_length=225, null=True)),
                ('recipient_account_number', models.CharField(blank=True, max_length=15, null=True)),
                ('transactionID', models.CharField(max_length=20, unique=True)),
                ('pending', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_user', to='auth.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_user', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('username', models.CharField(blank=True, max_length=225, null=True)),
                ('ref_number', models.CharField(blank=True, max_length=15, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('confirmedBy', models.CharField(blank=True, max_length=225, null=True)),
                ('transactionID', models.CharField(max_length=20, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposited_acct', to='General_Account.depositaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depositor', to='auth.user')),
            ],
        ),
    ]
