# Generated by Django 4.0 on 2022-04-07 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(blank=True, default='null', max_length=225, null=True)),
                ('ref_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('account_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('balance', models.BigIntegerField(default=0)),
                ('transaction_code', models.CharField(blank=True, default='0000', max_length=4, null=True)),
                ('interest_rate', models.BigIntegerField(blank=True, default=0, null=True)),
                ('block', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('emailVaried', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='auth.user')),
            ],
        ),
    ]
