# Generated by Django 4.0 on 2022-04-07 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('userName', models.CharField(blank=True, default='null', max_length=225, null=True)),
                ('balance', models.BigIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_temp_account', to='auth.user')),
            ],
        ),
    ]
