# Generated by Django 4.0 on 2022-04-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_temporaryaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='userName',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='temporaryaccount',
            name='userName',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
